- name: catalogue
  hosts: localhost # need to give instance name here by adding ip address of instace in inventory filed due to error i have used local host here
  become: yes
  tasks:
  - name: disable old version of nodejs  and enable new versio
    ansible.builtin.shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  
  - name: disable old nodejs and enable nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  
  - name: create roboshop user  
    ansible.builtin.user:
      name: roboshop

  - name: Recursively remove directory
    ansible.builtin.file:
      path: /app
      state: absent


  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download catalogue application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: extract catalogue application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: Install dependicies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: Copy Catalogue service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: deamon realod and start
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Copy mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb-client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present

  - name: get the categories product_count
    ansible.builtin.command: mongo --host <ip address of mongo> --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
    register: product_count

  - name: load catalogue data
    ansible.builtin.command: mongo --host mongodb.daws76s.online < /app/schema/catalogue.js
    when: product_count.stdout == "0" # keep double quotes

# when: product_count.stdout == 0
  - name: start and enable catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes