- name: mongodb
  hosts: localhost # need to give instance name here by adding ip address of instace in inventory filed due to error i have used local host here
  become: yes
  tasks:
  - name: Copy mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  

  - name: install mongo
    ansible.builtin.package:
      name: mongodb-org
      state: present


  - name: start and enable mongodb
    ansible.builtin.service:
      name: mongodb
      state: started
      enabled: yes

  - name: allow remote connections
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  
  - name: restart mongodb
    ansible.builtin.service:
      name: mongodb
      state: restarted
  
